### ISSUE TITLE
Traduzindo arquivo t-v.csv (time B)

### ISSUE THREAD

**Issue by claytonaalves** [PensePython/PensePython2#2]
Time B está trabalhando no arquivo: `t-v.csv`

**Comment by andrealmar** [comment]
@claytonaalves qual branch você está usando relacionados à tradução do arquivo t-v.csv?

**Comment by claytonaalves** [comment]
@andrealmar cria um fork desse repositório, aí o pessoal do time B pode fazer fork e pull request para seu repositório... aí revisamos e quando finalizar, fazemos um pull request revisado para cá novamente...

Ou se preferir eu já criei um fork... posso revisar, mas meu tempo durante o dia é corrido, só sobra tempo durante a noite.

**Comment by andrealmar** [comment]
Está criado em https://github.com/andrealmar/PensePython2

**Comment by claytonaalves** [comment]
Fiz um pull request no seu repositório... O interessante seria todos do time b fazerem os pull requests no teu repositório para revisão e depois vc faz um pull pra este repositório.

**Comment by claytonaalves** [comment]
Reabrindo... acho melhor fechar só quando estiver integrado.
